#!/bin/sh
set -e
lb config noauto \
  --mode debian \
  --distribution jammy \
  --parent-distribution jammy \
  --initramfs casper \
  --architectures amd64 \
  --linux-flavours generic \
  --bootloader syslinux \
  --syslinux-theme "" \
  --security false \
  --mirror-bootstrap "http://archive.ubuntu.com/ubuntu/" \
  --mirror-chroot "http://archive.ubuntu.com/ubuntu/" \
  --mirror-chroot-security "http://security.ubuntu.com/ubuntu/" \
  --mirror-binary "http://archive.ubuntu.com/ubuntu/" \
  --mirror-binary-security "http://security.ubuntu.com/ubuntu/" \
  --binary-images iso-hybrid \
  --debian-installer false \
  --memtest none \
  --iso-application "PRIMERS OS" \
  --iso-publisher "Primers Organisation" \
  --iso-volume "PRIMERS_OS_1.0" \
  --archive-areas "main restricted universe multiverse" \
  --apt-indices false \
  --cache false \
  "${@}"
