---
modules-search: [ local, /usr/lib/calamares/modules ]
sequence:
  - show:
    - welcome
  - exec:
    - locale
    - keyboard
    - partition
    - mount
    - unpackfs
    - machineid
    - fstab
    - locale
    - localecfg
    - users
    - networkcfg
    - hwclock
    - services-systemd
    - bootloader-config
    - grubcfg
    - bootloader
    - packages
    - initramfscfg
    - initramfs
    - removeuser
    - unmount
  - show:
    - finished
branding: primers
prompt-install: true
dont-chroot: false
